name = "kaiser-echo-api"
main = "api/index.ts"
compatibility_date = "2024-10-01"
node_compat = true

[vars]
ENVIRONMENT = "production"

# Add your secrets with: wrangler secret put <KEY>
# - GROQ_API_KEY
# - GOOGLE_TTS_API_KEY
# - SUPABASE_URL
# - SUPABASE_SERVICE_KEY
